apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      nodeSelector:
        kubernetes.io/hostname: tylerhpdesk
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        ports:
        - containerPort: 5678
        env:
        - name: N8N_HOST
          value: "0.0.0.0"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "http"
        - name: WEBHOOK_URL
          value: "http://n8n.homelab.local"
        - name: GENERIC_TIMEZONE
          value: "UTC"
        - name: N8N_LOG_LEVEL
          value: "info"
        - name: DB_TYPE
          value: "sqlite"
        - name: N8N_SECURE_COOKIE
          value: "false"
        volumeMounts:
        - name: n8n-storage
          mountPath: /home/node/.n8n
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 120
          timeoutSeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5678
          initialDelaySeconds: 60
          timeoutSeconds: 30
          periodSeconds: 15
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1000m
      volumes:
      - name: n8n-storage
        persistentVolumeClaim:
          claimName: n8n-storage