# =========================
# MetalLB IP pool
# =========================
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.210
---
# =========================
# MetalLB L2 advertisement
# =========================
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - pihole-pool
---
# =========================
# Pi-hole Deployment
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      nodeSelector:
        kubernetes.io/hostname: tbeles
      containers:
        - name: pihole
          image: pihole/pihole:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PIHOLE_DNS_
              value: "8.8.8.8;8.8.4.4"
            - name: FTLCONF_DNS_LISTENINGMODE
              value: "ALL"
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: dnsmasq-data
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-data
          hostPath:
            path: /var/lib/pihole
            type: DirectoryOrCreate
        - name: dnsmasq-data
          hostPath:
            path: /var/lib/pihole/dnsmasq
            type: DirectoryOrCreate
---
# =========================
# Pi-hole LoadBalancer Service
# =========================
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  labels:
    app: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.200
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: web
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-alt
      protocol: TCP
      port: 8080
      targetPort: 80
